[package]
name = "paddy_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
paddy_ptr = { path = "../paddy_ptr" }
paddy_utils = { path = "../paddy_utils" }

nonmax = "0.5.5"
fixedbitset = "0.5.7"
