[package]
name = "paddy_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.14.5"
ahash = "0.8.11"
tracing = { version = "0.1", default-features = false, features = ["std"] }
paddy_utils_proc_macros = { path = "macros" }

